import { Router } from 'express';
import { WebController } from '../controllers/web.controller';
import { AnalysisController } from '../controllers/analysis.controller';
import { AnalyticsController } from '../controllers/analytics.controller';
import { requireAdminAuth } from '../middlewares/adminAuth';
import { TrackedPlayerController } from '../controllers/trackedPlayer.controller';

const router = Router();

const webAdminRouter = Router();
webAdminRouter.use(requireAdminAuth);
webAdminRouter.get('/dataset-stats', WebController.getDatasetStats);
webAdminRouter.post('/run-ingestion', WebController.triggerDatasetIngestion);
webAdminRouter.get('/ml-observability', WebController.getMlObservabilityStatus);
webAdminRouter.post('/ml-drift-job', WebController.runDriftJob);
webAdminRouter.post('/ml-rollback', WebController.triggerMlRollback);
webAdminRouter.all('/precompute', AnalyticsController.triggerPrecomputation);
webAdminRouter.post('/retry-failed-analytics', AnalyticsController.retryFailed);
webAdminRouter.get('/tracked-players/search', TrackedPlayerController.search);
webAdminRouter.post('/tracked-players/track', TrackedPlayerController.track);
webAdminRouter.post('/tracked-players/bootstrap', TrackedPlayerController.bootstrap);
webAdminRouter.post('/tracked-players/reindex-csv', TrackedPlayerController.reindexCsv);
webAdminRouter.post('/tracked-players/daily-update', TrackedPlayerController.dailyUpdate);
webAdminRouter.post('/tracked-players/sync', TrackedPlayerController.syncAll);
webAdminRouter.post('/tracked-players/:id/sync', TrackedPlayerController.syncOne);
router.use('/admin', webAdminRouter);

router.get('/landing', WebController.getLandingData);
router.get('/config', WebController.getConfig);
router.get('/tournaments/catalog', WebController.getTournamentsCatalog);
router.get('/tournaments/:tourneyName/history', WebController.getTournamentHistoryDetails);
router.get('/tournaments/live', WebController.getLiveTournaments);
router.get('/tournaments/today', WebController.getTodayTournaments);
router.get('/tournaments/date/:date', WebController.getTournamentsByDate);
router.get('/pool/stats', WebController.getPoolStats);
router.get('/pool/persistent-stats', WebController.getPersistentPoolStats);
router.post('/pool/ensure-match', WebController.ensureMatchData);
router.get('/tracked-players', TrackedPlayerController.list);
router.get('/tracked-players/:id/archive', TrackedPlayerController.getArchive);
router.get('/tracked-players/:id/matches/:indexId/bundle', TrackedPlayerController.getMatchBundle);
router.get('/tracked-players/:id', TrackedPlayerController.getStatus);
router.get('/rankings/:tour', WebController.getRankings);
router.get('/players', WebController.getPlayers);
router.get('/players/:playerName/ranking-history', WebController.getPlayerRankingHistory);
router.get('/players/:playerName/surface-stats', WebController.getPlayerSurfaceStatsFromPool);
router.get('/players/:playerName/analysis-bundle', WebController.getPlayerAnalysisBundle);
router.get('/historical-match-features', WebController.getHistoricalMatchFeatures);
router.get('/validated-layer-audit', WebController.getValidatedLayerAudit);
router.get('/backtest-matches', WebController.getBacktestMatchCandidates);
router.get('/players/:playerId/image', WebController.getPlayerImage);
router.get('/players/:slugOrId', WebController.getPlayerDetails);
router.get('/h2h/:p1Id/:p2Id', WebController.getHeadToHead);
router.get('/h2h-history', WebController.getHistoricalH2H);
router.get('/matches', WebController.getMatches);
router.get('/matches/deep-analytics', WebController.getMatchDeepAnalytics);
router.get('/matches/:eventId/stats', WebController.getEventStatsAndOdds);
router.get('/matches/:fixtureId/analytics', AnalyticsController.getMatchAnalytics);
router.get('/matches/:idOrSlug/editorial', AnalysisController.getMatchEditorial);

export const webRoutes = router;
