/**
 * Comprehensive End-to-End Multilingual Pipeline Test (Step 4)
 *
 * Verifies the complete 3-phase lifecycle:
 * Phase 1: Zero-dependency i18n dictionary & language direction
 * Phase 2: Dynamic 5-language AI analysis generation & DB storage
 * Phase 3: Multilingual SEO bundle generation & SSR rendering
 *
 * Run with: npx tsx scripts/test_e2e_multilingual.ts
 */

import Database from 'better-sqlite3';
import { SeoRendererService } from '../src/services/seo-renderer.service';
import { projectPredictionToLanguage } from '../src/utils/multilingualProjection';

async function runEndToEndTest() {
  console.log('🚀 Starting Full End-to-End Multilingual Verification (Step 4)...\n');

  const fixtureId = 99917066;
  const homePlayerName = 'Alexander Zverev';
  const awayPlayerName = 'Daniil Medvedev';
  const tournName = 'Rolex Paris Masters, ATP 1000';
  const surface = 'Hardcourt indoor';
  const roundName = 'Final';
  const slug = 'alexander-zverev-vs-daniil-medvedev-99917066';
  const baseUrl = 'https://ptin-ai.com';

  // ─── 1. SIMULATE FULL 5-LANGUAGE AI ANALYSIS (PHASE 2) ─────────────────────
  console.log('1️⃣ Simulating Phase 2 Multi-Language AI Analysis Generation...');
  const multilingualAiSummary = {
    en: 'At the Paris Masters final, Alexander Zverev faces Daniil Medvedev in a high-intensity indoor hardcourt showdown. Both players excel from the baseline with high rally tolerance.',
    fa: 'در فینال مسترز پاریس، الکساندر زورف و دانیل مدودف در یک فینال تمام‌عیار در زمین هارد سرپوشیده به مصاف یکدیگر می‌روند. هر دو بازیکن در رالی‌های طولانی انتهای زمین تبحر بالایی دارند.',
    ar: 'في نهائي بطولة باريس للماسترز، يلتقي ألكسندر زفيريف مع دانييل ميدفيديف في مواجهة قمة داخل القاعات المغلقة. يمتلك كلاهما قدرة استثنائية على خوض التبادلات الطويلة.',
    tr: 'Paris Masters finalinde Alexander Zverev ile Daniil Medvedev kapali sert kortta karsi karsiya geliyor. Iki raket de arka cizgide yuksek ralli direncine sahip.',
    pt: 'Na grande final do Masters de Paris, Alexander Zverev e Daniil Medvedev medem forças em quadra rápida coberta. Ambos se destacam pela consistência e trocas de bola no fundo de quadra.',
  };

  const multilingualKeyFactors = {
    en: ['1st Serve dominance: Zverev 78% vs Medvedev 73%', 'Dominance Ratio: Zverev 1.18', 'Deciding set tiebreak clutch efficiency'],
    fa: ['برتری سرویس اول: زورف ۷۸٪ در برابر مدودف ۷۳٪', 'نسبت تسلط بر مسابقه (DR): ۱.۱۸ برای زورف', 'عملکرد کلاچ در تای‌بریک ست سوم'],
    ar: ['تفوق الإرسال الأول: زفيريف 78% مقابل 73% لميدفيديف', 'نسبة الهيمنة في الملعب (DR): 1.18 لصالح زفيريف', 'الكفاءة الحاسمة في شوط كسر التعادل'],
    tr: ['1. Servis ustunlugu: Zverev %78 vs Medvedev %73', 'Ustunluk Orani (DR): Zverev 1.18', 'Karar seti tie-break performans basarisi'],
    pt: ['Superioridade no 1º serviço: Zverev 78% vs Medvedev 73%', 'Razão de Dominância (DR): Zverev 1.18', 'Eficiência mental e clutch em tie-breaks decisivos'],
  };

  console.log('✓ 5-Language AI analysis bundle created successfully.');

  // ─── 2. SIMULATE PHASE 3 MULTILINGUAL SEO BUNDLE ───────────────────────────
  console.log('\n2️⃣ Creating Phase 3 Multilingual SEO Bundle (as generated by state football)...');
  const hreflangAlternates = [
    { lang: 'x-default', href: `${baseUrl}/match/${slug}` },
    { lang: 'en', href: `${baseUrl}/match/${slug}?lang=en` },
    { lang: 'fa', href: `${baseUrl}/match/${slug}?lang=fa` },
    { lang: 'tr', href: `${baseUrl}/match/${slug}?lang=tr` },
    { lang: 'pt', href: `${baseUrl}/match/${slug}?lang=pt` },
    { lang: 'ar', href: `${baseUrl}/match/${slug}?lang=ar` },
  ];

  const multilingualSeo = {
    en: {
      lang: 'en',
      metaTitle: 'Alexander Zverev vs Daniil Medvedev Preview',
      metaDescription: multilingualAiSummary.en,
      h1Proposal: 'Alexander Zverev vs Daniil Medvedev: Match Analysis — Rolex Paris Masters',
      openGraph: { title: 'Alexander Zverev vs Daniil Medvedev Preview', description: multilingualAiSummary.en },
      twitterCard: { title: 'Alexander Zverev vs Daniil Medvedev Preview', description: multilingualAiSummary.en },
      schemaJsonLd: { '@context': 'https://schema.org', '@graph': [{ '@type': 'SportsEvent', inLanguage: 'en', name: 'Alexander Zverev vs Daniil Medvedev Preview' }] },
    },
    fa: {
      lang: 'fa',
      metaTitle: 'تحلیل Alexander Zverev vs Daniil Medvedev',
      metaDescription: multilingualAiSummary.fa,
      h1Proposal: 'Alexander Zverev vs Daniil Medvedev: تحلیل تخصصی مسابقه — Rolex Paris Masters',
      openGraph: { title: 'تحلیل Alexander Zverev vs Daniil Medvedev', description: multilingualAiSummary.fa },
      twitterCard: { title: 'تحلیل Alexander Zverev vs Daniil Medvedev', description: multilingualAiSummary.fa },
      schemaJsonLd: { '@context': 'https://schema.org', '@graph': [{ '@type': 'SportsEvent', inLanguage: 'fa', name: 'تحلیل Alexander Zverev vs Daniil Medvedev' }] },
    },
    ar: {
      lang: 'ar',
      metaTitle: 'تحليل Alexander Zverev vs Daniil Medvedev',
      metaDescription: multilingualAiSummary.ar,
      h1Proposal: 'Alexander Zverev vs Daniil Medvedev: تحليل المباراة التكتيكي — Rolex Paris Masters',
      openGraph: { title: 'تحليل Alexander Zverev vs Daniil Medvedev', description: multilingualAiSummary.ar },
      twitterCard: { title: 'تحليل Alexander Zverev vs Daniil Medvedev', description: multilingualAiSummary.ar },
      schemaJsonLd: { '@context': 'https://schema.org', '@graph': [{ '@type': 'SportsEvent', inLanguage: 'ar', name: 'تحليل Alexander Zverev vs Daniil Medvedev' }] },
    },
    tr: {
      lang: 'tr',
      metaTitle: 'Alexander Zverev vs Daniil Medvedev Analizi',
      metaDescription: multilingualAiSummary.tr,
      h1Proposal: 'Alexander Zverev vs Daniil Medvedev: Maç Analizi — Rolex Paris Masters',
      openGraph: { title: 'Alexander Zverev vs Daniil Medvedev Analizi', description: multilingualAiSummary.tr },
      twitterCard: { title: 'Alexander Zverev vs Daniil Medvedev Analizi', description: multilingualAiSummary.tr },
      schemaJsonLd: { '@context': 'https://schema.org', '@graph': [{ '@type': 'SportsEvent', inLanguage: 'tr', name: 'Alexander Zverev vs Daniil Medvedev Analizi' }] },
    },
    pt: {
      lang: 'pt',
      metaTitle: 'Prévia Alexander Zverev vs Daniil Medvedev',
      metaDescription: multilingualAiSummary.pt,
      h1Proposal: 'Alexander Zverev vs Daniil Medvedev: Análise Tática — Rolex Paris Masters',
      openGraph: { title: 'Prévia Alexander Zverev vs Daniil Medvedev', description: multilingualAiSummary.pt },
      twitterCard: { title: 'Prévia Alexander Zverev vs Daniil Medvedev', description: multilingualAiSummary.pt },
      schemaJsonLd: { '@context': 'https://schema.org', '@graph': [{ '@type': 'SportsEvent', inLanguage: 'pt', name: 'Prévia Alexander Zverev vs Daniil Medvedev' }] },
    },
  };

  const storedSeoPayload = {
    titleTag: multilingualSeo.en.metaTitle,
    metaDescription: multilingualSeo.en.metaDescription,
    canonicalSlug: slug,
    canonicalUrl: `${baseUrl}/match/${slug}`,
    hreflangAlternates,
    multilingual: multilingualSeo,
  };

  // ─── 3. UPSERT INTO TELEGRAM-BACKEND SQLITE DB ─────────────────────────────
  console.log('\n3️⃣ Upserting test match to telegram-backend database.sqlite...');
  const db = new Database('./data/database.sqlite');

  // Insert into predictions
  db.prepare(`
    INSERT INTO predictions (
      fixture_id, home_name, away_name, tournament_name, round_name, surface,
      predicted_winner, win_probability, confidence, status, ai_summary, key_factors, match_date, published_at, created_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(fixture_id) DO UPDATE SET
      ai_summary = excluded.ai_summary,
      key_factors = excluded.key_factors,
      tournament_name = excluded.tournament_name;
  `).run(
    fixtureId,
    homePlayerName,
    awayPlayerName,
    tournName,
    roundName,
    surface,
    homePlayerName,
    56,
    'HIGH',
    'SCHEDULED',
    JSON.stringify(multilingualAiSummary),
    JSON.stringify(multilingualKeyFactors),
    new Date().toISOString(),
    new Date().toISOString(),
    new Date().toISOString()
  );

  // Insert into match_editorials
  db.prepare(`
    INSERT INTO match_editorials (
      fixture_id, slug, headline, summary, tactical_analysis,
      seo_title, seo_description, seo_metadata_json, is_published, publish_status, created_at, updated_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(fixture_id) DO UPDATE SET
      seo_metadata_json = excluded.seo_metadata_json,
      slug = excluded.slug,
      is_published = excluded.is_published;
  `).run(
    fixtureId,
    slug,
    `${homePlayerName} vs ${awayPlayerName}: Final Match Analysis — ${tournName}`,
    multilingualAiSummary.en,
    'Tactical analysis breakdown...',
    multilingualSeo.en.metaTitle,
    multilingualSeo.en.metaDescription,
    JSON.stringify(storedSeoPayload),
    1,
    'published',
    new Date().toISOString(),
    new Date().toISOString()
  );

  console.log('✓ Successfully saved to predictions and match_editorials tables in SQLite.');

  // ─── 4. VERIFY SSR RENDERING ACROSS ALL 5 LANGUAGES ───────────────────────
  console.log('\n4️⃣ Verifying telegram-backend SSR Render across all 5 languages...');
  const matchData = SeoRendererService.findMatch(String(fixtureId));
  if (!matchData) {
    throw new Error('FAIL: SeoRendererService.findMatch could not locate test match!');
  }
  console.log(`✓ Match found via findMatch: slug = ${matchData.slug}`);

  const testLangs = ['fa', 'ar', 'tr', 'pt', 'en'] as const;

  for (const lang of testLangs) {
    console.log(`\n--- Verifying SSR for [${lang.toUpperCase()}] ---`);
    const html = SeoRendererService.renderHtml(matchData.prediction, matchData.slug, baseUrl, lang);

    // 1. Root tag & direction
    const expectedDir = lang === 'fa' || lang === 'ar' ? 'rtl' : 'ltr';
    const expectedHtmlTag = `<html lang="${lang}" dir="${expectedDir}">`;
    if (!html.includes(expectedHtmlTag)) {
      throw new Error(`FAIL: Missing ${expectedHtmlTag} in ${lang} HTML!`);
    }
    console.log(`  ✓ Root tag: ${expectedHtmlTag}`);

    // 2. Title length <= 60 chars and intact player names
    const titleMatch = html.match(/<title>(.*?)<\/title>/);
    if (!titleMatch) throw new Error(`FAIL: Missing <title> in ${lang} HTML`);
    const title = titleMatch[1];
    console.log(`  ✓ Title (${title.length} chars): "${title}"`);
    if (title.length > 60) {
      throw new Error(`FAIL: Title length > 60 in ${lang}: ${title.length}`);
    }
    if (!title.includes('Alexander Zverev') || !title.includes('Daniil Medvedev')) {
      throw new Error(`FAIL: Latin player names not preserved in ${lang} title!`);
    }

    // 3. Description matches target language
    const descMatch = html.match(/<meta name="description" content="(.*?)" \/>/);
    if (!descMatch) throw new Error(`FAIL: Missing description in ${lang} HTML`);
    const desc = descMatch[1];
    console.log(`  ✓ Description (${desc.length} chars): "${desc.slice(0, 60)}..."`);
    if (desc.length > 160) {
      throw new Error(`FAIL: Description length > 160 in ${lang}: ${desc.length}`);
    }

    // 4. OpenGraph locale
    const expectedLocales: Record<string, string> = {
      fa: 'fa_IR',
      ar: 'ar_SA',
      tr: 'tr_TR',
      pt: 'pt_BR',
      en: 'en_US',
    };
    if (!html.includes(`<meta property="og:locale" content="${expectedLocales[lang]}" />`)) {
      throw new Error(`FAIL: og:locale mismatch in ${lang}`);
    }
    console.log(`  ✓ og:locale: ${expectedLocales[lang]}`);

    // 5. Font injection
    if (lang === 'fa') {
      if (!html.includes('Vazirmatn')) throw new Error('FAIL: Vazirmatn font missing in FA HTML');
      if (html.includes('Noto+Sans+Arabic')) throw new Error('FAIL: Arabic font leaked into FA HTML');
      console.log('  ✓ Correct font: Vazirmatn loaded');
    } else if (lang === 'ar') {
      if (!html.includes('Noto+Sans+Arabic')) throw new Error('FAIL: Noto Sans Arabic font missing in AR HTML');
      if (html.includes('Vazirmatn')) throw new Error('FAIL: Persian font leaked into AR HTML');
      console.log('  ✓ Correct font: Noto Sans Arabic loaded');
    } else {
      if (html.includes('Vazirmatn') || html.includes('Noto+Sans+Arabic')) {
        throw new Error(`FAIL: RTL fonts leaked into Western ${lang} HTML`);
      }
      console.log('  ✓ Correct font: Western Outfit loaded');
    }

    // 6. Hreflang alternates
    for (const altLang of ['x-default', 'en', 'fa', 'tr', 'pt', 'ar']) {
      if (!html.includes(`hreflang="${altLang}"`)) {
        throw new Error(`FAIL: Missing hreflang="${altLang}" in ${lang} HTML`);
      }
    }
    console.log('  ✓ All 6 hreflang links verified in <head>');
  }

  // ─── 5. VERIFY MULTILINGUAL PROJECTION FOR WEBAPP API ENDPOINTS ────────────
  console.log('\n5️⃣ Verifying Backend API Projection for WebApp (?lang= query parameter)...');
  for (const lang of testLangs) {
    const projected = projectPredictionToLanguage(matchData.prediction, lang);
    console.log(`[API ${lang.toUpperCase()}] ai_summary (type: ${typeof projected.ai_summary}):`);
    console.log(`  "${(projected.ai_summary as string).slice(0, 70)}..."`);
    if (typeof projected.ai_summary !== 'string') {
      throw new Error(`FAIL: API projection for ${lang} did not return pure string!`);
    }
    if (lang === 'fa' && !(projected.ai_summary as string).includes('مسترز پاریس')) {
      throw new Error('FAIL: FA projection text mismatch');
    }
    if (lang === 'ar' && !(projected.ai_summary as string).includes('بطولة باريس')) {
      throw new Error('FAIL: AR projection text mismatch');
    }
    if (lang === 'tr' && !(projected.ai_summary as string).includes('Paris Masters')) {
      throw new Error('FAIL: TR projection text mismatch');
    }
    if (lang === 'pt' && !(projected.ai_summary as string).includes('Masters de Paris')) {
      throw new Error('FAIL: PT projection text mismatch');
    }
  }

  console.log('\n🎉 ALL 5-LANGUAGE END-TO-END PIPELINE TESTS PASSED WITH 100% SUCCESS!\n');
}

runEndToEndTest()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('❌ E2E Multilingual Test Failed:', err);
    process.exit(1);
  });
